<a href="https://colab.research.google.com/github/Fidi000/CSCI-191/blob/main/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd
import math
import plotly.express as px
import random
import time
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [107]:
F = lambda w, x:  sum([W*X for W,X in zip(w,x)])
G = lambda y: 1/(1+np.exp(-y))

def predict(model, x): 
  w1 = model[0]
  w2 = model[1]
  v1 = model[2]
  z1 = G(F(w1,x))
  z2 = G(F(w2, x))
  Z = (1, z1, z2)
  y = G(F(v1, Z))
  return y

def classify(Y):
  return [1 if y > 0/5 else 0 for y in Y]

In [108]:
data = [((0,0), 0), ((0,1), 1), ((1,0), 1), ((1,1), 0)]
squaredError = []
accuracy = []

In [109]:
def rand_Init():
    return np.random.uniform(-0.01, 0.01, 3)

Initial Random weights & Learning Rate


In [110]:
alpha = 0.3
w1 = rand_Init()
w2 = rand_Init()
v1 = rand_Init()
model = [w1,w2, v1]
print("Learning Rate: ", alpha, "\n")
print("w1: ", w1, "\n")
print("w2: ", w2, "\n")
print("v1: ", v1, "\n")
print("model: ", model)

Learning Rate:  0.3 

w1:  [ 0.00064968  0.00772718 -0.00369379] 

w2:  [-0.00242524 -0.00826455  0.00242038] 

v1:  [-0.00519887 -0.00164381 -0.00157176] 

model:  [array([ 0.00064968,  0.00772718, -0.00369379]), array([-0.00242524, -0.00826455,  0.00242038]), array([-0.00519887, -0.00164381, -0.00157176])]


In [111]:
def backProp(iter, model, data, learningRate):
  W1 = model[0]
  W2 = model[1]
  V1 = model[2]
  for i in range(iter):
    np.random.shuffle(data)
    if (i % 5000) == 0: #every 1000 epochs, the squared error and accuracy is tracked
      X = [(1, x1, x2) for ((x1, x2),r) in data]
      R = [r for ((x1, x2),r) in data]
      yPred = [predict([W1, W2, V1], x) for x in X]
      classPredict = classify(yPred)
      accuracy.append(sklearn.metrics.accuracy_score(R, classPredict))
      squaredError.append(sum([pow(r - y, 2) for (r, y) in zip(R, yPred)]))
    for (x, r) in data:
      z1 = G(F(W1, x))
      z2 = G(F(W2, x))
      Z = (1, z1, z2)
      y = G(F(V1,Z))
      deltV = [learningRate * (r - y) * z for z in Z]
      deltW1 = [learningRate * (r - y) * V1[1] * z1 * (1 - z1) * xi for xi in x]
      deltW2 = [learningRate * (r - y) * V1[2] * z2 * (1 - z2) * xi for xi in x]

      V1 = [v + dv for (v, dv) in zip(V1, deltV)]
      W1 = [w + dw for (w, dw) in zip(W1, deltW1)]
      W2 = [w + dw for (w, dw) in zip(W2, deltW2)]

  return [W1, W2, V1]

Final Weights

In [112]:
model = backProp(50000, model, data, alpha)
print(model)

[[-10.60537582423769, -10.604788786216956], [-10.716519057699786, -10.715934913191505], [0.6921796171394582, -8.895099157398148, -9.854708433190336]]


Output for the model

In [113]:
print("Testing Data:", data)
yPredicted = [predict(model, x) for x in X]
print("Y Predictions:", yPredicted)
print("Class Predictions:", classify(yPredicted))

Testing Data: [((1, 0), 1), ((0, 1), 1), ((0, 0), 0), ((1, 1), 0)]
Y Predictions: [0.6663540314131743, 0.6663540314131743, 0.6664516156181018, 0.6664516156181018]
Class Predictions: [1, 1, 1, 1]


Squared Error and Accuracy

In [114]:
#for i in enumerate(squaredError):
print("Squared Error: ", np.array(squaredError), "\n")
print("Accuracy: ", np.array(accuracy), "\n")

Squared Error:  [1.00001158 1.12347951 1.10363514 1.11130789 1.10927041 1.12577261
 1.1092733  1.11016425 1.12947738 1.10896325] 

Accuracy:  [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5] 



In [115]:
 print("The 5 different initial models:", "\n")
 models = []
 for i in range(5):
  w1 = rand_Init()
  w2 = rand_Init()
  v1 = rand_Init()
  model = [w1,w2, v1]
  models.append(model)
  print(str(i + 1) + ":",np.array(model), "\n")


The 5 different initial models: 

1: [[-0.00144849 -0.00265758  0.00454951]
 [-0.00533548 -0.00067842 -0.00027923]
 [-0.00601115  0.00483508 -0.00306854]] 

2: [[ 0.00793764  0.00282966  0.0031793 ]
 [ 0.00543641 -0.00109161  0.00930341]
 [-0.0003158   0.00145622  0.00398022]] 

3: [[-0.00865683  0.00749852  0.00585434]
 [ 0.00241885  0.00341865 -0.00668605]
 [ 0.00327231  0.00082881 -0.00774257]] 

4: [[ 0.00842087  0.00655444  0.00381076]
 [-0.00807409  0.00371412  0.00971003]
 [-0.00298273 -0.00622037  0.0024288 ]] 

5: [[-0.00939937  0.00348528  0.00803786]
 [ 0.00604898 -0.00786752 -0.00286641]
 [ 0.00722318 -0.00566945  0.00263734]] 



In [116]:
print("The 5 final models: ", "\n")
squaredError = [[] for i in range(len(models))]
for i, model in enumerate(models):
  models[i] = backProp(50000, model, data, alpha)

for i, model in enumerate(models):
  print(str(i + 1) + ":", "\n", np.array(model), "\n")

The 5 final models:  

1: 
 [list([-10.622284080435971, -10.621784608155284])
 list([-10.701304061399664, -10.70080330742186])
 list([0.6799353804924899, -9.034923461582919, -9.717651463261843])] 

2: 
 [list([-10.652157558556539, -10.65248935005405])
 list([-10.671577029273868, -10.671908600549996])
 list([0.7551259994823635, -9.2922171527576, -9.460055112221868])] 

3: 
 [list([-10.648884997579938, -10.648522995953948])
 list([-10.67566112461795, -10.675300090270307])
 list([0.677448008581785, -9.260512343918775, -9.491941729817313])] 

4: 
 [list([-10.638455179420339, -10.638385256476566])
 list([-10.685667450580201, -10.685599357994203])
 list([0.698150149744358, -9.172307021434023, -9.580303305217726])] 

5: 
 [list([-10.708195382998932, -10.708328114345722])
 list([-10.613187667442544, -10.61331889218132])
 list([0.6664871722372969, -9.786187219779228, -8.965679038419129])] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

