<a href="https://colab.research.google.com/github/Fidi000/CSCI-191/blob/main/Linear_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imported data



In [41]:
import random
import numpy as np
from sklearn import datasets
irisDS = datasets.load_iris()
X = irisDS.data[:, :4]
Y = irisDS.target

print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

**Linear Regression**



Train Model

In [42]:
from sklearn import linear_model
linReg = linear_model.LinearRegression()
linReg.fit(X,Y)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
linReg.coef_

array([-0.11190585, -0.04007949,  0.22864503,  0.60925205])

In [44]:
linReg.intercept_

0.186495247206249

In [54]:
linReg.predict(X,Y)

TypeError: ignored

Logistic Regression with MSE

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report, confusion_matrix

In [60]:
logRegMSE = LogisticRegression(solver='liblinear', C= 10, random_state=0)
logRegMSE.fit(X,Y)
logRegMSE.predict_log_proba(X)

array([[-9.95853601e-02, -2.35611961e+00, -2.26355618e+01],
       [-2.41881503e-01, -1.53781150e+00, -2.06421840e+01],
       [-1.57070410e-01, -1.92856856e+00, -2.10545579e+01],
       [-2.17343180e-01, -1.63298183e+00, -1.96215538e+01],
       [-8.02628988e-02, -2.56231084e+00, -2.26411884e+01],
       [-3.73262362e-02, -3.30666389e+00, -2.22136126e+01],
       [-9.43189552e-02, -2.40786195e+00, -2.03171501e+01],
       [-1.31488723e-01, -2.09385827e+00, -2.16226813e+01],
       [-2.71864498e-01, -1.43530608e+00, -1.89220550e+01],
       [-2.60280755e-01, -1.47331362e+00, -2.10930886e+01],
       [-7.44560920e-02, -2.63454277e+00, -2.36496155e+01],
       [-1.40945637e-01, -2.02902624e+00, -2.06115980e+01],
       [-2.79612615e-01, -1.41090095e+00, -2.09592370e+01],
       [-2.19251372e-01, -1.62515992e+00, -2.08020644e+01],
       [-2.97625963e-02, -3.52934722e+00, -2.70226369e+01],
       [-9.91083458e-03, -4.61907804e+00, -2.54961277e+01],
       [-2.47455815e-02, -3.71145561e+00

In [63]:
logRegMSE.coef_

array([[ 0.64422261,  2.25478505, -3.49210096, -1.6080433 ],
       [ 0.11325321, -2.3720629 ,  1.07251901, -2.4598705 ],
       [-2.86845575, -3.11540619,  4.44871264,  5.65618682]])

In [61]:
logRegMSE.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [62]:
confusion_matrix(Y, logRegMSE.predict(X))

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  2, 48]])

Logistic Regression with Cross Entropy

In [ ]:
CrossEntropy = sum([ r*log((y)) for r,y in zip(Y, yPredicted)])